/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WrappedRouteImport } from './routes/wrapped'
import { Route as TopologyRouteImport } from './routes/topology'
import { Route as RoastFriendRouteImport } from './routes/roast-friend'
import { Route as RoastRouteImport } from './routes/roast'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as LeaderboardsRouteImport } from './routes/leaderboards'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WebhooksRazorpayRouteImport } from './routes/webhooks.razorpay'
import { Route as WebhooksGithubRouteImport } from './routes/webhooks.github'
import { Route as ULoginRouteImport } from './routes/u.$login'
import { Route as TeamIdRouteImport } from './routes/team.$id'
import { Route as TSlugRouteImport } from './routes/t.$slug'
import { Route as RIdRouteImport } from './routes/r.$id'
import { Route as DevUsernameRouteImport } from './routes/dev.$username'
import { Route as ApiWorkerRouteImport } from './routes/api.worker'
import { Route as ApiGraphqlRouteImport } from './routes/api.graphql'
import { Route as ApiDocsRouteImport } from './routes/api.docs'
import { Route as ApiAnalyzeRouteImport } from './routes/api.analyze'
import { Route as InternalCronDrainRouteImport } from './routes/internal.cron.drain'
import { Route as ApiWebhookSlackRouteImport } from './routes/api.webhook.slack'
import { Route as ApiV1JobsJobIdRouteImport } from './routes/api.v1.jobs.$jobId'
import { Route as ApiAuthCallbackGithubRouteImport } from './routes/api.auth.callback.github'
import { Route as ApiV1ReposOwnerRepoVerdictRouteImport } from './routes/api.v1.repos.$owner.$repo.verdict'

const WrappedRoute = WrappedRouteImport.update({
  id: '/wrapped',
  path: '/wrapped',
  getParentRoute: () => rootRouteImport,
} as any)
const TopologyRoute = TopologyRouteImport.update({
  id: '/topology',
  path: '/topology',
  getParentRoute: () => rootRouteImport,
} as any)
const RoastFriendRoute = RoastFriendRouteImport.update({
  id: '/roast-friend',
  path: '/roast-friend',
  getParentRoute: () => rootRouteImport,
} as any)
const RoastRoute = RoastRouteImport.update({
  id: '/roast',
  path: '/roast',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardsRoute = LeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksRazorpayRoute = WebhooksRazorpayRouteImport.update({
  id: '/webhooks/razorpay',
  path: '/webhooks/razorpay',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksGithubRoute = WebhooksGithubRouteImport.update({
  id: '/webhooks/github',
  path: '/webhooks/github',
  getParentRoute: () => rootRouteImport,
} as any)
const ULoginRoute = ULoginRouteImport.update({
  id: '/u/$login',
  path: '/u/$login',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIdRoute = TeamIdRouteImport.update({
  id: '/team/$id',
  path: '/team/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugRoute = TSlugRouteImport.update({
  id: '/t/$slug',
  path: '/t/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RIdRoute = RIdRouteImport.update({
  id: '/r/$id',
  path: '/r/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DevUsernameRoute = DevUsernameRouteImport.update({
  id: '/dev/$username',
  path: '/dev/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkerRoute = ApiWorkerRouteImport.update({
  id: '/api/worker',
  path: '/api/worker',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGraphqlRoute = ApiGraphqlRouteImport.update({
  id: '/api/graphql',
  path: '/api/graphql',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api/docs',
  path: '/api/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeRoute = ApiAnalyzeRouteImport.update({
  id: '/api/analyze',
  path: '/api/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalCronDrainRoute = InternalCronDrainRouteImport.update({
  id: '/internal/cron/drain',
  path: '/internal/cron/drain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhookSlackRoute = ApiWebhookSlackRouteImport.update({
  id: '/api/webhook/slack',
  path: '/api/webhook/slack',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1JobsJobIdRoute = ApiV1JobsJobIdRouteImport.update({
  id: '/api/v1/jobs/$jobId',
  path: '/api/v1/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackGithubRoute = ApiAuthCallbackGithubRouteImport.update({
  id: '/api/auth/callback/github',
  path: '/api/auth/callback/github',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ReposOwnerRepoVerdictRoute =
  ApiV1ReposOwnerRepoVerdictRouteImport.update({
    id: '/api/v1/repos/$owner/$repo/verdict',
    path: '/api/v1/repos/$owner/$repo/verdict',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/referrals': typeof ReferralsRoute
  '/roast': typeof RoastRoute
  '/roast-friend': typeof RoastFriendRoute
  '/topology': typeof TopologyRoute
  '/wrapped': typeof WrappedRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/docs': typeof ApiDocsRoute
  '/api/graphql': typeof ApiGraphqlRoute
  '/api/worker': typeof ApiWorkerRoute
  '/dev/$username': typeof DevUsernameRoute
  '/r/$id': typeof RIdRoute
  '/t/$slug': typeof TSlugRoute
  '/team/$id': typeof TeamIdRoute
  '/u/$login': typeof ULoginRoute
  '/webhooks/github': typeof WebhooksGithubRoute
  '/webhooks/razorpay': typeof WebhooksRazorpayRoute
  '/api/webhook/slack': typeof ApiWebhookSlackRoute
  '/internal/cron/drain': typeof InternalCronDrainRoute
  '/api/auth/callback/github': typeof ApiAuthCallbackGithubRoute
  '/api/v1/jobs/$jobId': typeof ApiV1JobsJobIdRoute
  '/api/v1/repos/$owner/$repo/verdict': typeof ApiV1ReposOwnerRepoVerdictRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/referrals': typeof ReferralsRoute
  '/roast': typeof RoastRoute
  '/roast-friend': typeof RoastFriendRoute
  '/topology': typeof TopologyRoute
  '/wrapped': typeof WrappedRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/docs': typeof ApiDocsRoute
  '/api/graphql': typeof ApiGraphqlRoute
  '/api/worker': typeof ApiWorkerRoute
  '/dev/$username': typeof DevUsernameRoute
  '/r/$id': typeof RIdRoute
  '/t/$slug': typeof TSlugRoute
  '/team/$id': typeof TeamIdRoute
  '/u/$login': typeof ULoginRoute
  '/webhooks/github': typeof WebhooksGithubRoute
  '/webhooks/razorpay': typeof WebhooksRazorpayRoute
  '/api/webhook/slack': typeof ApiWebhookSlackRoute
  '/internal/cron/drain': typeof InternalCronDrainRoute
  '/api/auth/callback/github': typeof ApiAuthCallbackGithubRoute
  '/api/v1/jobs/$jobId': typeof ApiV1JobsJobIdRoute
  '/api/v1/repos/$owner/$repo/verdict': typeof ApiV1ReposOwnerRepoVerdictRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/referrals': typeof ReferralsRoute
  '/roast': typeof RoastRoute
  '/roast-friend': typeof RoastFriendRoute
  '/topology': typeof TopologyRoute
  '/wrapped': typeof WrappedRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/docs': typeof ApiDocsRoute
  '/api/graphql': typeof ApiGraphqlRoute
  '/api/worker': typeof ApiWorkerRoute
  '/dev/$username': typeof DevUsernameRoute
  '/r/$id': typeof RIdRoute
  '/t/$slug': typeof TSlugRoute
  '/team/$id': typeof TeamIdRoute
  '/u/$login': typeof ULoginRoute
  '/webhooks/github': typeof WebhooksGithubRoute
  '/webhooks/razorpay': typeof WebhooksRazorpayRoute
  '/api/webhook/slack': typeof ApiWebhookSlackRoute
  '/internal/cron/drain': typeof InternalCronDrainRoute
  '/api/auth/callback/github': typeof ApiAuthCallbackGithubRoute
  '/api/v1/jobs/$jobId': typeof ApiV1JobsJobIdRoute
  '/api/v1/repos/$owner/$repo/verdict': typeof ApiV1ReposOwnerRepoVerdictRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/explore'
    | '/leaderboards'
    | '/referrals'
    | '/roast'
    | '/roast-friend'
    | '/topology'
    | '/wrapped'
    | '/api/analyze'
    | '/api/docs'
    | '/api/graphql'
    | '/api/worker'
    | '/dev/$username'
    | '/r/$id'
    | '/t/$slug'
    | '/team/$id'
    | '/u/$login'
    | '/webhooks/github'
    | '/webhooks/razorpay'
    | '/api/webhook/slack'
    | '/internal/cron/drain'
    | '/api/auth/callback/github'
    | '/api/v1/jobs/$jobId'
    | '/api/v1/repos/$owner/$repo/verdict'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/explore'
    | '/leaderboards'
    | '/referrals'
    | '/roast'
    | '/roast-friend'
    | '/topology'
    | '/wrapped'
    | '/api/analyze'
    | '/api/docs'
    | '/api/graphql'
    | '/api/worker'
    | '/dev/$username'
    | '/r/$id'
    | '/t/$slug'
    | '/team/$id'
    | '/u/$login'
    | '/webhooks/github'
    | '/webhooks/razorpay'
    | '/api/webhook/slack'
    | '/internal/cron/drain'
    | '/api/auth/callback/github'
    | '/api/v1/jobs/$jobId'
    | '/api/v1/repos/$owner/$repo/verdict'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/explore'
    | '/leaderboards'
    | '/referrals'
    | '/roast'
    | '/roast-friend'
    | '/topology'
    | '/wrapped'
    | '/api/analyze'
    | '/api/docs'
    | '/api/graphql'
    | '/api/worker'
    | '/dev/$username'
    | '/r/$id'
    | '/t/$slug'
    | '/team/$id'
    | '/u/$login'
    | '/webhooks/github'
    | '/webhooks/razorpay'
    | '/api/webhook/slack'
    | '/internal/cron/drain'
    | '/api/auth/callback/github'
    | '/api/v1/jobs/$jobId'
    | '/api/v1/repos/$owner/$repo/verdict'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  ExploreRoute: typeof ExploreRoute
  LeaderboardsRoute: typeof LeaderboardsRoute
  ReferralsRoute: typeof ReferralsRoute
  RoastRoute: typeof RoastRoute
  RoastFriendRoute: typeof RoastFriendRoute
  TopologyRoute: typeof TopologyRoute
  WrappedRoute: typeof WrappedRoute
  ApiAnalyzeRoute: typeof ApiAnalyzeRoute
  ApiDocsRoute: typeof ApiDocsRoute
  ApiGraphqlRoute: typeof ApiGraphqlRoute
  ApiWorkerRoute: typeof ApiWorkerRoute
  DevUsernameRoute: typeof DevUsernameRoute
  RIdRoute: typeof RIdRoute
  TSlugRoute: typeof TSlugRoute
  TeamIdRoute: typeof TeamIdRoute
  ULoginRoute: typeof ULoginRoute
  WebhooksGithubRoute: typeof WebhooksGithubRoute
  WebhooksRazorpayRoute: typeof WebhooksRazorpayRoute
  ApiWebhookSlackRoute: typeof ApiWebhookSlackRoute
  InternalCronDrainRoute: typeof InternalCronDrainRoute
  ApiAuthCallbackGithubRoute: typeof ApiAuthCallbackGithubRoute
  ApiV1JobsJobIdRoute: typeof ApiV1JobsJobIdRoute
  ApiV1ReposOwnerRepoVerdictRoute: typeof ApiV1ReposOwnerRepoVerdictRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wrapped': {
      id: '/wrapped'
      path: '/wrapped'
      fullPath: '/wrapped'
      preLoaderRoute: typeof WrappedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topology': {
      id: '/topology'
      path: '/topology'
      fullPath: '/topology'
      preLoaderRoute: typeof TopologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roast-friend': {
      id: '/roast-friend'
      path: '/roast-friend'
      fullPath: '/roast-friend'
      preLoaderRoute: typeof RoastFriendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roast': {
      id: '/roast'
      path: '/roast'
      fullPath: '/roast'
      preLoaderRoute: typeof RoastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboards': {
      id: '/leaderboards'
      path: '/leaderboards'
      fullPath: '/leaderboards'
      preLoaderRoute: typeof LeaderboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks/razorpay': {
      id: '/webhooks/razorpay'
      path: '/webhooks/razorpay'
      fullPath: '/webhooks/razorpay'
      preLoaderRoute: typeof WebhooksRazorpayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks/github': {
      id: '/webhooks/github'
      path: '/webhooks/github'
      fullPath: '/webhooks/github'
      preLoaderRoute: typeof WebhooksGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$login': {
      id: '/u/$login'
      path: '/u/$login'
      fullPath: '/u/$login'
      preLoaderRoute: typeof ULoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$id': {
      id: '/team/$id'
      path: '/team/$id'
      fullPath: '/team/$id'
      preLoaderRoute: typeof TeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug': {
      id: '/t/$slug'
      path: '/t/$slug'
      fullPath: '/t/$slug'
      preLoaderRoute: typeof TSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$id': {
      id: '/r/$id'
      path: '/r/$id'
      fullPath: '/r/$id'
      preLoaderRoute: typeof RIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/$username': {
      id: '/dev/$username'
      path: '/dev/$username'
      fullPath: '/dev/$username'
      preLoaderRoute: typeof DevUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/worker': {
      id: '/api/worker'
      path: '/api/worker'
      fullPath: '/api/worker'
      preLoaderRoute: typeof ApiWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/graphql': {
      id: '/api/graphql'
      path: '/api/graphql'
      fullPath: '/api/graphql'
      preLoaderRoute: typeof ApiGraphqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/docs': {
      id: '/api/docs'
      path: '/api/docs'
      fullPath: '/api/docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze': {
      id: '/api/analyze'
      path: '/api/analyze'
      fullPath: '/api/analyze'
      preLoaderRoute: typeof ApiAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/cron/drain': {
      id: '/internal/cron/drain'
      path: '/internal/cron/drain'
      fullPath: '/internal/cron/drain'
      preLoaderRoute: typeof InternalCronDrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhook/slack': {
      id: '/api/webhook/slack'
      path: '/api/webhook/slack'
      fullPath: '/api/webhook/slack'
      preLoaderRoute: typeof ApiWebhookSlackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/jobs/$jobId': {
      id: '/api/v1/jobs/$jobId'
      path: '/api/v1/jobs/$jobId'
      fullPath: '/api/v1/jobs/$jobId'
      preLoaderRoute: typeof ApiV1JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback/github': {
      id: '/api/auth/callback/github'
      path: '/api/auth/callback/github'
      fullPath: '/api/auth/callback/github'
      preLoaderRoute: typeof ApiAuthCallbackGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/repos/$owner/$repo/verdict': {
      id: '/api/v1/repos/$owner/$repo/verdict'
      path: '/api/v1/repos/$owner/$repo/verdict'
      fullPath: '/api/v1/repos/$owner/$repo/verdict'
      preLoaderRoute: typeof ApiV1ReposOwnerRepoVerdictRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  ExploreRoute: ExploreRoute,
  LeaderboardsRoute: LeaderboardsRoute,
  ReferralsRoute: ReferralsRoute,
  RoastRoute: RoastRoute,
  RoastFriendRoute: RoastFriendRoute,
  TopologyRoute: TopologyRoute,
  WrappedRoute: WrappedRoute,
  ApiAnalyzeRoute: ApiAnalyzeRoute,
  ApiDocsRoute: ApiDocsRoute,
  ApiGraphqlRoute: ApiGraphqlRoute,
  ApiWorkerRoute: ApiWorkerRoute,
  DevUsernameRoute: DevUsernameRoute,
  RIdRoute: RIdRoute,
  TSlugRoute: TSlugRoute,
  TeamIdRoute: TeamIdRoute,
  ULoginRoute: ULoginRoute,
  WebhooksGithubRoute: WebhooksGithubRoute,
  WebhooksRazorpayRoute: WebhooksRazorpayRoute,
  ApiWebhookSlackRoute: ApiWebhookSlackRoute,
  InternalCronDrainRoute: InternalCronDrainRoute,
  ApiAuthCallbackGithubRoute: ApiAuthCallbackGithubRoute,
  ApiV1JobsJobIdRoute: ApiV1JobsJobIdRoute,
  ApiV1ReposOwnerRepoVerdictRoute: ApiV1ReposOwnerRepoVerdictRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
