/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ULoginRouteImport } from './routes/u.$login'
import { Route as TeamIdRouteImport } from './routes/team.$id'
import { Route as TSlugRouteImport } from './routes/t.$slug'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ULoginRoute = ULoginRouteImport.update({
  id: '/u/$login',
  path: '/u/$login',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIdRoute = TeamIdRouteImport.update({
  id: '/team/$id',
  path: '/team/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugRoute = TSlugRouteImport.update({
  id: '/t/$slug',
  path: '/t/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/t/$slug': typeof TSlugRoute
  '/team/$id': typeof TeamIdRoute
  '/u/$login': typeof ULoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/t/$slug': typeof TSlugRoute
  '/team/$id': typeof TeamIdRoute
  '/u/$login': typeof ULoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/t/$slug': typeof TSlugRoute
  '/team/$id': typeof TeamIdRoute
  '/u/$login': typeof ULoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/t/$slug' | '/team/$id' | '/u/$login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/t/$slug' | '/team/$id' | '/u/$login'
  id: '__root__' | '/' | '/dashboard' | '/t/$slug' | '/team/$id' | '/u/$login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  TSlugRoute: typeof TSlugRoute
  TeamIdRoute: typeof TeamIdRoute
  ULoginRoute: typeof ULoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$login': {
      id: '/u/$login'
      path: '/u/$login'
      fullPath: '/u/$login'
      preLoaderRoute: typeof ULoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$id': {
      id: '/team/$id'
      path: '/team/$id'
      fullPath: '/team/$id'
      preLoaderRoute: typeof TeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug': {
      id: '/t/$slug'
      path: '/t/$slug'
      fullPath: '/t/$slug'
      preLoaderRoute: typeof TSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  TSlugRoute: TSlugRoute,
  TeamIdRoute: TeamIdRoute,
  ULoginRoute: ULoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
